url: "http://chichi-berlin.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true


prose:
  siteurl: "http://chichi-berlin.github.io"
  media: "images"
  ignore:
    - css
    - .gitignore
    - _config.yml
    - /_layouts
    - /_includes
    - images
    - index.md
    - CNAME
